CREATE DATABASE nykaa_marketing;

USE nykaa_marketing;


#KPIs
# Click‑Through Rate (CTR):

SELECT Campaign_ID,
       (Clicks * 100.0 / Impressions) AS CTR
FROM nykaa_campaigns
LIMIT 1000;

SELECT Campaign_ID,
       (Conversions * 100.0 / Clicks) AS Conversion_Rate
FROM nykaa_campaigns;

SELECT Campaign_ID,
       ((Revenue - Acquisition_Cost) / Revenue) * 100 AS Profit_Margin
FROM nykaa_campaigns;


SELECT Campaign_ID,
       (Revenue / Conversions) AS ARPC
FROM nykaa_campaigns;


SELECT Campaign_ID,
       (Acquisition_Cost / Conversions) AS CPA
FROM nykaa_campaigns;


# top 5 campaigns by roi
SELECT Campaign_ID, ROI
FROM nykaa_campaigns
ORDER BY ROI DESC
LIMIT 5;

# Which Campaign Type Generate the highest ROI overall?
Select Campaign_Type,
sum(Revenue) AS Total_Revenue,
Sum(Acquisition_Cost) AS Total_Cost,
ROUND(
	((SUM(Revenue)-sum(Acquisition_Cost))/ NULLIF(SUM(Acquisition_Cost),0))*100,
    2
) AS roi_percentage
From nykaa_campaigns
Group By Campaign_type
Order by roi_percentage DESC
LIMIT 1;



# What is the average CTR across all campaigns?
SELECT 
	Campaign_ID,
    Campaign_Type,
    Target_Audience,
    Conversions,
    Clicks,
    (CAST(Conversions AS FLOAT) / NULLIF(Clicks,0)) *100 AS Conversion_Rate
FROM nykaa_campaigns
ORDER BY Conversion_Rate DESC
LIMIT 5;


# Which campaigns had the highest conversion rate?
SELECT 
	Campaign_ID,
    Campaign_Type,
    Target_Audience,
    Conversions,
    Clicks,
    (CAST(Conversions AS FLOAT) / NULLIF(Clicks,0)) *100 AS Conversion_Rate
FROM nykaa_campaigns
ORDER BY Conversion_Rate DESC
LIMIT 1;


# How does campaign duration affect conversions?
SELECT
	Duration,
    SUM(Conversions) AS Total_Conversions,
    AVG(Conversions) AS Avg_Conversions_Per_Campaign
FROM nykaa_campaigns
Group by Duration
Order by Duration;

SELECT 
    Duration,
    SUM(Conversions) * 100.0 / NULLIF(SUM(Clicks), 0) AS Conversion_Rate
FROM nykaa_campaigns
GROUP BY Duration
ORDER BY Conversion_Rate DESC;
# Which language campaigns performed better in terms of engagement score?
Select 
	Language,
    AVG (Engagement_Score) AS Avg_Engagement_score,
    SUM(Engagement_Score) AS Total_Engagement_score,
    Count(*) AS Campaign_Count
From nykaa_campaigns
Group by Language
Order by Avg_Engagement_score desc;

# Audience Insights
# Which target audience segment delivered the most revenue?
select 
	Target_Audience,
    Sum(Revenue) as total_revenue,
    Avg(Revenue) as avg_revenue,
    COUNT(*) as campaign_count
    
From nykaa_campaigns
group by Target_Audience
Order by total_revenue DESC;

# Do college student campaigns have higher CTR compared to working women campaigns?
select 
	Target_Audience,
    Sum(Clicks)*100.0 / NULLIF(SUM(Impressions),0) AS CTR
    
From nykaa_campaigns
Where Target_Audience in ('College Student','Working Women')
Group by Target_Audience
Order by CTR DESC;

# Which customer segment has the highest profit margin?
SELECT 
    Customer_Segment,
    SUM(Revenue) AS Total_Revenue,
    SUM(Acquisition_Cost) AS Total_Cost,
    ((SUM(Revenue) - SUM(Acquisition_Cost)) * 100.0 / NULLIF(SUM(Revenue), 0)) AS Profit_Margin
FROM nykaa_campaigns
GROUP BY Customer_Segment
ORDER BY Profit_Margin DESC;


    


# How does engagement score vary across different target audiences?

SELECT 
    Target_Audience,
    AVG(Engagement_Score) AS Avg_Engagement_Score,
    SUM(Engagement_Score) AS Total_Engagement_Score,
    COUNT(*) AS Campaign_Count
FROM nykaa_campaigns
GROUP BY Target_Audience
ORDER BY Avg_Engagement_Score DESC;


# Which audience segment has the lowest acquisition cost per conversion?
SELECT 
    Customer_Segment,
    SUM(Acquisition_Cost) AS Total_Cost,
    SUM(Conversions) AS Total_Conversions,
    (SUM(Acquisition_Cost) * 1.0 / NULLIF(SUM(Conversions), 0)) AS Cost_Per_Conversion
FROM nykaa_campaigns
GROUP BY Customer_Segment
ORDER BY Cost_Per_Conversion ASC;

#  Financial Impact
# What is the total revenue generated by all campaigns?
select
    Sum(Revenue) as Total_Revenue
from nykaa_campaigns;


# Which campaign type has the highest profit margin?
SELECT 
    Campaign_Type,
    SUM(Revenue) AS Total_Revenue,
    SUM(Acquisition_Cost) AS Total_Cost,
    ((SUM(Revenue) - SUM(Acquisition_Cost)) * 100.0 / NULLIF(SUM(Revenue), 0)) AS Profit_Margin
FROM nykaa_campaigns
GROUP BY Campaign_Type
ORDER BY Profit_Margin DESC;

# How does acquisition cost compare across campaign types?

SELECT 
    Campaign_Type,
    SUM(Acquisition_Cost) AS Total_Acquisition_Cost,
    AVG(Acquisition_Cost) AS Avg_Acquisition_Cost_Per_Campaign,
    COUNT(*) AS Campaign_Count
FROM nykaa_campaigns
GROUP BY Campaign_Type
ORDER BY Total_Acquisition_Cost DESC;


# Which campaigns delivered negative ROI (loss‑making)?

SELECT 
    Campaign_ID,
    Campaign_Type,
    Target_Audience,
    Revenue,
    Acquisition_Cost,
    ((Revenue - Acquisition_Cost) * 100.0 / NULLIF(Acquisition_Cost, 0)) AS ROI
FROM nykaa_campaigns
WHERE (Revenue - Acquisition_Cost) < 0
ORDER BY ROI ASC;

# What is the average revenue per conversion (ARPC) across campaigns?

SELECT 
    SUM(Revenue) * 1.0 / NULLIF(SUM(Conversions), 0) AS Avg_Revenue_Per_Conversion
FROM nykaa_campaigns;
